<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Optimize>true</Optimize>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../NowUI.Desktop/NowUI.Desktop.csproj" />
  </ItemGroup>
</Project>
